# Generated by Django 3.2.15 on 2024-02-22 10:46

from django.db import migrations


def create_orderdetails_cost(apps, schema_editor):
    Order_details = apps.get_model('foodcartapp', 'Order_details')

    for order_detail in Order_details.objects.all().iterator():
        order_detail.cost = order_detail.product.price * order_detail.quantity
        order_detail.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20240214_1121'),
    ]

    operations = [migrations.RunPython(create_orderdetails_cost)
    ]
