# Generated by Django 3.2.15 on 2024-02-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20240205_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказчик', 'verbose_name_plural': 'заказчики'},
        ),
    ]
