# Generated by Django 3.2.15 on 2024-02-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='order_details',
            old_name='product_count',
            new_name='quantity',
        ),
    ]
