# Generated by Django 3.2.15 on 2024-03-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_details_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New order is accepted'), ('P', 'Order is being prepared'), ('D', 'Delivery'), ('C', 'Completed')], db_index=True, default='N', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
