# Generated by Django 3.2.15 on 2024-03-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_prepared', to='foodcartapp.restaurant', verbose_name='Ресторан, где готовят заказ'),
        ),
    ]
