# Generated by Django 3.2.15 on 2024-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Долгота'),
        ),
    ]
