# Generated by Django 3.2.15 on 2024-06-17 11:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_location'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
                ('coordinates', django.db.models.manager.Manager()),
            ],
        ),
    ]
