# Generated by Django 3.2.15 on 2024-06-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_restaurant_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
            ],
        ),
    ]
