# Generated by Django 3.2.15 on 2024-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_restaurant_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Долгота'),
        ),
    ]
