# Generated by Django 3.2.15 on 2024-06-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20240618_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_details',
            new_name='OrderDetails',
        ),
    ]
