# Generated by Django 3.2.15 on 2024-07-28 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20240718_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Стоимость'),
        ),
    ]
